### ISSUE TITLE
CORS problem 

### ISSUE THREAD

**Issue by marchalb** [RobSchilderr/capacitor-supertokens-nextjs-turborepo#2]
Try to use the live example first ( https://www.next-capacitor-supertokens.app/) 

But it does not seem to work because of CORS issue .. 

In my console I see the following error: 
register:1 Access to fetch at 'https://next-capacitor-supertokens.app/api/auth/session/refresh' from origin 'https://www.next-capacitor-supertokens.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by RobSchilderr** [comment]
> Try to use the live example first ( https://www.next-capacitor-supertokens.app/)
> 
> But it does not seem to work because of CORS issue ..
> 
> In my console I see the following error: register:1 Access to fetch at 'https://next-capacitor-supertokens.app/api/auth/session/refresh' from origin 'https://www.next-capacitor-supertokens.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

Ah that was a Vercel issue, I had my domain configured to use `www` at the beginning.
