### ISSUE TITLE
Error on yarn build in next-app

### ISSUE THREAD

**Issue by anastasiosyal** [RobSchilderr/capacitor-supertokens-nextjs-turborepo#6]
From apps\next-app 

running yarn build results in the following

../../packages/ui/containers/Login/Login.tsx:207:12
Type error: Type '{}' is missing the following properties from type '{ hasRequestedCode: boolean; setHasRequestedCode: (value: 
boolean) => void; isGettingCode: boolean; setIsGettingCode: (value: boolean) => void; }': hasRequestedCode, setHasRequestedCode, isGettingCode, setIsGettingCode

  205 | 
  206 |         <div className="mt-6">
> 207 |           <PasswordlessLoginForm />
      |            ^
  208 |         </div>
  209 |       </AuthLayout>
  210 |     </>
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

![image](https://user-images.githubusercontent.com/20316953/232326651-2880bbe9-cb73-4bf7-8c82-b0d6ba39ccf9.png)

**Comment by RobSchilderr** [comment]
I fixed it!

I added a more modern UI/UX and updated some packages. I only did this for the Passwordless form with Thirdparty though. If people would like me to update the rest, let me know. :)

 <img width="375" alt="Screenshot_2023-02-20_at_6 00 08_PM" src="https://user-images.githubusercontent.com/35261620/232318901-c4bb8eeb-aa04-42f3-bc33-82cbc454ebc9.png">
